language: node_js

services:
  - docker

before_install:
  - docker build -t thefuzzyjew/supportdesk-backend ./backend
  - docker run -d -p 127.0.0.1:80:3000 thefuzzyjew/supportdesk-backend
  - docker ps -a

script: cd backend && npm test
